version: '3.8'

services:
  # n8n:
  #   build:
  #     context: ./n8n
  #   ports:
  #     - "5678:5678"
  #   volumes:
  #     - n8n_data:/data
  #   restart: always

  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    # depends_on:
    #   - n8n
    #   - ollama
    restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3001:3001" # Updated: Maps container port 5173 (Vite default) to host port 5173
  #   volumes:
  #     - ./frontend:/app  # Mount local frontend directory to /app in container
  #     - /app/node_modules  # Preserve node_modules in container
  #   restart: always

  frontend-nextjs:
    build:
      context: ./frontend-nextjs
    ports:
      - "3002:3000" # Next.js runs on port 3000 by default
    volumes:
      - ./frontend-nextjs:/app  # Mount local directory for hot reloading
      - /app/node_modules  # Preserve container's node_modules
      - /app/.next  # Preserve Next.js build cache
    restart: always

volumes:
  n8n_data:
